spring:
  datasource:
    url: jdbc:mysql://192.168.80.128:3306/spring-cloud?useUnicode=true&characterEncoding=utf8&characterSetResult=utf8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.qyj.qyjcloud.qyjcloudauth.mapper

